import Head from 'next/head'
import styles from './styles.module.css'
import iconUser from "../../../../assets/icon.jpeg"
import iconLocalizacao from "../../../../assets/iconLocalizacao.png"
import Navbar from '../../../../components/Navbar'
import Image from 'next/image'
import React, { FormEvent, ChangeEvent, useState } from "react"
import {useRef, useEffect} from "react"

export default function CadastroUsuario() {
  const [image, setImage] = useState();
  const [preview, setPreview] = useState();
  const fileInputRef = useRef();
  useEffect(() => {
    if(image){
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result);
      };
      reader.readAsDataURL(image);
    }else{
      setPreview(null);
    }
  }, [image]);

  return (
    <div className={styles.container}>
      <Head>
        <title>iCast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        <main className={styles.main}>
          <div className={styles.blocoCadastro}>
            <div className={styles.criarUsuario}>
              <p className={styles.titleCadUser}>iCast</p>
              <p className={styles.subtitleCadUser}>Crie uma conta gratuitamente preenchendo o formulario</p>
            </div>
            <div className={styles.blocoFormulario} style={{padding:'0px 60px 0px 60px'}}>
              <div style={{display:'flex', flexDirection:'column', width:'100%'}}>
                  <label className={styles.label}>Nome do episódio</label>
                  <input className={styles.input}></input>
              </div>
              <div style={{display:'flex', flexDirection:'row', width:'100%'}}>
                <div style={{display:'flex', flexDirection:'column', width:'47%'}}>
                  <label className={styles.label}>Nome</label>
                  <input className={styles.input}></input>
                </div>
                <div style={{display:'flex', flexDirection:'column', marginLeft:'20px', width:'47%'}}>
                  <label className={styles.label}>Sobrenome</label>
                  <input className={styles.input}></input>
                </div>
              </div>
                <div style={{display:'flex', flexDirection:'column', width:'100%'}}>
                    <label className={styles.label}>Senha</label>
                    <input className={styles.input}></input>
                </div>
                <div style={{display:'flex', flexDirection:'row', width:'100%'}}>
                  <div style={{display:'flex', flexDirection:'column', width:'47%'}}>
                    <label className={styles.label}>Estado</label>
                    <input className={styles.input}></input>
                  </div>
                  <div style={{display:'flex', flexDirection:'column', marginLeft:'20px', width:'47%'}}>
                    <label className={styles.label}>Cidade</label>
                    <input className={styles.input}></input>
                  </div>
              </div>
              <div style={{display:'flex', flexDirection:'column'}}>
              <label className={styles.label}>Avatar</label>
                {preview ? (
                  <img style={{height:'60px', width:'80px', objectFit: 'cover',
                   cursor: 'pointer', borderRadius:'4px'}}
                    src={preview} 
                    onClick={() => {
                      setImage(null);
                    }}></img>
                ) : (
                  <button 
                    style={{height:'60px', width:'80px', objectFit: 'cover', 
                    background:'white', border: '1px solid #98AFCA', 
                    color: '#6F7782', fontWeight: '500', fontSize:'34px',
                    borderRadius: '4px', cursor: 'pointer'}}
                    onClick={(event) => {
                    event.preventDefault();
                    fileInputRef.current.click();
                  }}>
                    +</button>
                )}
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  style={{display: "none"}}
                  accept="image/*"
                  onChange={(event) => {
                    const file = event.target.files[0];
                    if(file && file.type.substr(0, 5) === "image"){
                      setImage(file);
                    }else{
                      setImage(null);
                    }
                  }}
                  >
                  </input>
                  <button className={styles.buttonEnviar}>Salvar cadastro</button>
                  <div style={{display:'flex', flexDirection: 'row', widt: '100%', justifyContent: 'center'}}>
                    <p className={styles.login}>Já possui uma conta? </p>
                    <p className={styles.login} style={{color: '#0094FF'}}> &nbsp;&nbsp;Faça login </p>
                    </div>
                </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}