import Head from 'next/head'
import styles from './styles.module.css'

import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"

import { FiSearch } from 'react-icons/fi'

import Navbar from '../../../../components/Navbar'
import Player from '../../components/PodcastPlayer'
import PodcastList from '../../components/PodcastList'

import { api } from '../../../../service/api'
import { useState, useContext, useEffect } from 'react'

import { AuthContext } from '../../../../contexts/Authentication'

export default function Home() {
  const { isAuthenticated } = useContext(AuthContext);
  const [ podcasts, setPodcasts ] = useState([]) 

  useEffect(() => { 
    if(isAuthenticated) {
      api.get('podcast').then(response => {
        setPodcasts(response.data)
      })
    }
  }, [isAuthenticated])

  return (
    <div className={styles.container}>
      <Head>
        <title>iCast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        <div><Navbar/></div>
        <div className={styles.main}>
          <div className={styles.search}>
            <input type="text" id="search"/>
            <div className={styles.icon}><FiSearch/></div>
          </div>
          <h2 className={styles.pageTitle}>RESULTADOS</h2>
          <div className={styles.results}>
            {podcasts?.map((podcast) => (
              <PodcastList 
                key={podcast.id} 
                id={podcast.id}
                title={podcast.title}
                author={`${podcast.author.firstName} ${podcast.author.lastName}`}
                url={podcast.coverUrl} 
                description={podcast.description}
                countEpisodes={podcast.Episode.length}
              />
            ))}
          </div>
        </div>
        <div className={styles.player}>
          <Player/>
        </div>
      </div>
    </div>
  )
}

