import Head from 'next/head'
import styles from './styles.module.css'
import iconLocalizacao from "../../../../assets/iconLocalizacao.png"
import Image from 'next/image'
import React from "react"
import { useState, useContext, useEffect } from 'react'
import { AuthContext } from "../../../../contexts/Authentication"

export default function UserProfile() {
    const { user, role } = useContext(AuthContext);

    const [ url, setUrl ] = useState("");
    const [ username, setUsername ] = useState("");
    const [ localization, setLocalization ] = useState("");

    useEffect(() => {
        if(user) {
            setUrl(user.avatar[0].filename)
            setUsername(`${user.firstName} ${user.lastName}`)
            setLocalization(`${user.city}, ${user.state}`)
        }
    }, [user])

  return (
    <div className={styles.container}>
      <Head>
        <title>iCast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <div className={styles.informacoes}>
            <div className={styles.informacoes__perfil}>
              {url && (
                <Image 
                    src={url}
                    alt={url}
                    width={70}
                    height={70}
                    layout="fixed"
                    quality={90}
                    style={{borderRadius:'50px'}}
                />
                )}
              <div className={styles.organizarInformacoes}>
                <p>{username}</p>
                <div className={styles.organizarEndereco}>
                  <Image 
                      src={iconLocalizacao}
                      alt={"localização"}
                      width={30}
                      height={15}
                      className={styles.imgEndereco}
                  />
                    <p>{localization}</p>
                  </div>
              </div>
            </div>
            {role === 'PODCASTER' ? (
              <button className={styles.buttonStatus}>Podcaster</button>
            ) : (
              <button className={styles.buttonStatus}>Ouvinte</button>
            )}
            
          </div> 
    </div>
  )
}