import Head from 'next/head'
import styles from './styles.module.css'

import { api } from '../../../../service/api'
import { useState, useContext, useEffect } from 'react'
import { AuthContext } from '../../../../contexts/Authentication'

import Navbar from '../../../../components/Navbar'
import PodcastList from '../../components/PodcastList'
import UserProfile from '../../components/UserPerfil'

export default function Home() {
  const { isAuthenticated } = useContext(AuthContext);
  const [ podcasts, setPodcasts ] = useState([]) 
  const [ spotlights, setSpotlights ] = useState([]) 


  useEffect(() => { 
    if(isAuthenticated) {
      api.get('podcast').then(response => {
        setPodcasts(response.data)
      })
    }
  }, [isAuthenticated])
  
  useEffect(() => { 
    if(isAuthenticated) {
      api.get('podcasts/spotlights').then(response => {
        setSpotlights(response.data)
      })
    }
  }, [isAuthenticated])

  return (
    <div className={styles.container}>
      <Head>
        <title>iCast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        <Navbar/>
        <div>
          <UserProfile/>
          <div style={{marginLeft:'110px'}}>
          <h2 className={styles.pageTitle} style={{fontSize:'19px', marginTop:'40px', marginBottom:'20px'}}>Publique</h2>
          <div style={{display:'flex'}}>
            <a href="/cadastrar/podcast">
              <button style={{border:'1px solid #473080', color: '#473080', fontWeight:'200', cursor:'pointer',
                fontFamily:'Montserrat, sans-serif', background:'none', width:'110px', height:'80px', display:'flex', 
                flexDirection:'column', alignItems:'center' }}>
                <p style={{fontSize:'45px', marginTop:'-6px'}}>+</p>
                <p style={{fontSize:'10px', marginTop:'-40px'}}>Criar podcast</p>
              </button>
            </a>
            <a href="/cadastrar/episodio">
              <button style={{border:'1px solid #473080', color: '#473080', fontWeight:'200', marginLeft:'30px', cursor:'pointer',
              fontFamily:'Montserrat, sans-serif', background:'none', width:'110px', height:'80px', display:'flex', 
              flexDirection:'column', alignItems:'center' }}>
              <p style={{fontSize:'45px', marginTop:'-6px'}}>+</p>
              <p style={{fontSize:'10px', marginTop:'-40px'}}>Adicionar episodio</p>
              </button>  
            </a>
          </div>
              <h2 className={styles.pageTitle}>Seus Podcasts</h2>
              <div className={styles.feed}>
                {podcasts?.map((podcast) => (
                  <PodcastList 
                    key={podcast.id} 
                    id={podcast.id}
                    title={podcast.title}
                    author={`${podcast.author.firstName} ${podcast.author.lastName}`}
                    url={podcast.coverUrl} 
                    description={podcast.description}
                    countEpisodes={podcast.Episode.length}
                  />
                ))}
              </div>
          </div>
        </div>
      </div>
    </div>
  );
}

